spring:
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:cheesse}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  sql:
    init:
      mode: always
